version: "3.9"  
services:
  web_api:
    image: "frankinstaen/patientwebapi"
    build: . 
    container_name: web_api_application
    ports:
      - "5141:80"
    networks: 
       - xyz-network
  sql:
    image: "mcr.microsoft.com/mssql/server"
    container_name: sql_server
    ports: 
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=MyPass@word
    networks: 
       - xyz-network

networks:
  xyz-network:
    driver: "bridge"